### ISSUE TITLE
phone번호 자료형

### ISSUE THREAD

**Issue by yjhykim** [yjhykim/HelloWorld#20]
전화번호는 현재 start/mid/end로 각각 int 형으로 관리되고 있습니다.
0으로 시작하는 경우가 많이 있는데, 매번 입/출력시에 변환해야 할텐데
그냥 string으로 사용하는 것은 어떨까요 ?
검색의 효율과도 연계하여 검토 부탁합니다.

**Comment by jhkim-610** [comment]
생일도 마찬가지 일까요?

**Comment by yjhykim** [comment]
> 

생일은 앞에 0을 채워넣지는 않으니 관계 없지 않을까요?

**Comment by jiminnn95** [comment]
저는 검색은 전체 자료에 대해 수행하지만 출력은 최대 5개 이므로 int 가 낫지 않을 까 생각했습니다. 그리고 아마 생일도 동일할 것 같아요 이게 생년월일로 출력이 되어서 - 20220216 이런식이라, 월,일이 한자리수면 채워넣어야 합니다~

**Comment by yjhykim** [comment]
알겠습니다. 그럼 그냥 기존대로 하고 출력단에서 형식 변경하는걸로 이해하겠습니다.

**Comment by HyebinAN** [comment]
출력단인 Printer에서 대응 가능하도록 수정하겠습니다.

**Comment by yjhykim** [comment]
IO에서 formatting을 하여 처리하기로 하였으므로 close 합니다.
