### ISSUE TITLE
Column -> Employee 변환기를 IOHandler와 공유 필요

### ISSUE THREAD

**Issue by yjhykim** [yjhykim/HelloWorld#21]
dbms의 mod는 인터페이스가 아래와 같이 정의되어 있습니다.
Column from, string fromData, Column to, string toData
from에 해당하는 data들을 search 후 일괄적으로 각 employee들을 수정해야 하는데,
IOHandler에서도 매 입력건에 대하여 비슷한 작업을 수행할 것으로 예상합니다.
void editColumn(Employee* target, Column type,  string data) 과 같은 형식으로 data parser를 공유하는 것이 어떨까요 ?

**Comment by jhkim-610** [comment]
`IOHandler에서도 매 입력건에 대하여 비슷한 작업을 수행할 것으로 예상합니다.`
IOHandler에서 어떤 비슷한 작업을 예상하시나요?
저는 IOHandler에서 `dbms->mod(col1,data1,col2,data2);`이렇게 호출만하는 것으로 생각했습니다.

**Comment by jiminnn95** [comment]
저도 정호님과 비슷하게 생각했는데, 구체적인 예상 작업 공유해주시면 좋을 것 같습니다!

**Comment by yjhykim** [comment]
IOHandler에서는 전체 Employee를 따라서 parsing해서 string을 만들면 되니 Column에 따라 Employee 어떤 맴버에게 값을 할당할지 결정하는 부분은 없어도 되겠네요.
mod는 Column에 대해 어떤 Employee의 field를 update 할 지 구분해주는 부분이 필요합니다.
알겠습니다. 그럼 저 부분은 dbms에서만 사용하는 것으로 하겠습니다.

**Comment by yjhykim** [comment]
적용 불필요한 것으로 결론나 close 합니다.
