### ISSUE TITLE
빌드 오류

### ISSUE THREAD

**Issue by yjhykim** [yjhykim/HelloWorld#26]
![image](https://user-images.githubusercontent.com/82810373/154176580-19c3270d-0d47-406b-a18f-bf9fa7c8d96c.png)

확인하여 주시면 감사하겠습니다.

**Comment by jiminnn95** [comment]
아,.. 정의가 저 CL&, CERTI& 부분이 레퍼런스가 전부 빠져야 하는데, 제가 테스트만 업데이트 한다고 파일을 제외하고 커밋해서 누락되엇나 봅니다 ㅠㅠ

**Comment by jiminnn95** [comment]
PR#24 확인해주시면 감사하겠습니다 ㅠㅠ
