### ISSUE TITLE
DataBase의 타입문제

### ISSUE THREAD

**Issue by jiminnn95** [yjhykim/HelloWorld#31]
저희가 DB안에는 Employee 자체를 가지고 있고, 이후에 search, mod, del등 다른 db를 다루는 함수등 에서는 포인터 타입을 통해서 다루기로 했던 걸로 기억하는데,

DataBase 구현 내에 아래와 같이 적혀있어 이슈 남깁니다.
```
private:
    std::list<Employee*> database_;
```
Employee*가 아니라 Employee 가 되어야 하지 않을까요? 혹시 제가 잘못 이해했다면 코멘트 부탁드립니다.
또, deleteTargets 함수가 약간 비 효율적인 것 같아요, 아마 iterator 형식이어야 해서 이렇게 된거 같은데 같이 논의 해보았으면 좋겠습니다..!

**Comment by yjhykim** [comment]
네 저도 generic이 Employee이 되어야 storage로서 역할이 가능할 것 같습니다.

**Comment by yjhykim** [comment]
네 deleteTargets가 비효율적으로 보입니다. sch 후 delete를 하는 것이 아니라 sch와 delete를 동시에 처리해야 하지 않을까요?

**Comment by HyebinAN** [comment]
말씀하신것처럼 원래 std::list<Employee> 로 설계를 했었는데 delete랑 search 하면서 iterator 로 대응코자 pointer로 바꿔서 해봤던걸 올려버린것 같습니다 이건 수정하도록 하겠습니다!

**Comment by HyebinAN** [comment]
deleteTargets 는 서치하여 삭제할 데이터만 인자로 넘겨주는 것이 아닌가요!?

**Comment by jiminnn95** [comment]
넵 맞는데, 구현문제라기보다 효율적인 방법이 있을 지 함께 논의하고 싶어서요! 지금 방식은 db를 두번 돌게 되는 것 같아서 ㅠㅠ

**Comment by yjhykim** [comment]
> 

네 맞아요. 두번 돌게될 뿐 아니라 훨신 더 비효율적으로 돌게 됩니다.
delete는 search와 동일하게 동작하되, search 결과에 대해 result list에 append 하면서 동시에 db에서 삭제하느게 어떨까요?

**Comment by HyebinAN** [comment]
맞아요 효율적으로 하려면 Database로 조건을 넘겨서 한번 돌때 Search와 delete 하는게 맞을것 같습니다..!

**Comment by yjhykim** [comment]
> deleteTargets 는 서치하여 삭제할 데이터만 인자로 넘겨주는 것이 아닌가요!?

현재 인터페이스는 그렇게 되어 있습니다.

**Comment by HyebinAN** [comment]
원래 설계할땐 Search 로 얻은 employee pointer로 바로 접근해서 delete 하려는 의도였는데.. 변경하는것이 좋을 것 같습니다.ㅜㅜ

**Comment by jiminnn95** [comment]
그런데 저희 삭제는 하더라도 출력은 잘 되어야 하는거죠? 그러면 삭제에 대해서는 포인터 리스트가 아니라 list<Employee> 자체를 넘겨 주어야 하겠네요ㅠ!

**Comment by yjhykim** [comment]
> 그런데 저희 삭제는 하더라도 출력은 잘 되어야 하는거죠? 그러면 삭제에 대해서는 포인터 리스트가 아니라 list 자체를 넘겨 주어야 하겠네요ㅠ!

그러네요...

**Comment by HyebinAN** [comment]
네 출력되어야합니다 ㅠ 그럼 searchEngine에서 삭제까지 하시려는건가요?

**Comment by jiminnn95** [comment]
PPT를 다시 읽어보고 왔는데,... DEL의 경우도 삭제 전 출력이 필요하고 MOD의 경우도 변경전의 데이터를 출력해야 해서... SearchEngine에서 삭제를 바로 진행하는게 얼마나 효율적인지 약간 의문이 들긴 합니다ㅠ

**Comment by HyebinAN** [comment]
헉 변경전의 데이터군요........... 이건 서치해서 조건데이터 출력하고 난 뒤에 변경해야하네요 
서치하면서 변경전 데이터를 따로 담아서 넘겨야겠군요

**Comment by jiminnn95** [comment]
db의 경우 map 타입으로 변경하고, 데이터를 출력하는 경우 최대 5개의 레코드만 출력하므로 백업하여 사용하기로 논의되었습니다. close 합니다.
