### ISSUE TITLE
Solution 구성 건

### ISSUE THREAD

**Issue by yjhykim** [yjhykim/HelloWorld#46]
현재 solution 구조 하에서는 EMS가 exe/lib를 선택적으로 빌드하므로 solution 전체 run 시 동시에 main과 unit test를 실행이 불가합니다.
따라서 방안으로는 2가지가 있는데, 
1. EMS와 동일 구조를 갖고 source는 공유하되 output만 lib로 가지는 EMS_LIB project를 생성하는 방안
2. EMS_TEST에 EMS의 source를 공유하여 source hierarchy를 그대로 가지도록 설정해 주는 방법
일단 현재 떠오르는 안은 이렇게 2가지 입니다.

추후 refactoring 진행 시에 구조를 변경하면 좋을 것 같습니다.

**Comment by jiminnn95** [comment]
1번 이해가 됐는데 2번 같은 경우는 조금 더 설명 가능해주실 수 있으실까요? ㅠ EMS는 exe로 빌드하게 되는건가요?

**Comment by yjhykim** [comment]
> 1번 이해가 됐는데 2번 같은 경우는 조금 더 설명 가능해주실 수 있으실까요? ㅠ EMS는 exe로 빌드하게 되는건가요?

2번 같은경우는 EMS는 동일하게 exe output이구요, source는 EMS에 위치하되, EMS_TEST에 동일하게 해당 파일들을 경로 추가해서 연결해서 사용하는 방법입니다. EMS의 main은 가져오지 않으니 main은 EMS_TEST쪽에서 동작하게 됩니다.

**Comment by jiminnn95** [comment]
아, 이해했습니다. 소스가 많으면 헷갈리니 전 1번이 더 좋아보이긴 합니다 :)

**Comment by HyebinAN** [comment]
저도 지민님과 같은 생각입니다! 깔끔한것 같아요

**Comment by yjhykim** [comment]
알겠습니다. 다른 의견 없으시면 1번 안으로 진행하도록 하겠습니다. 혹시 이견 있으시면 코멘트 부탁드립니다.

**Comment by yjhykim** [comment]
정상적으로 완료되어 close 합니다.
